/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dawarly;

/**
 *
 * @author nono
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Regester = new javax.swing.JButton();
        LogIn = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Regester.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Regester.setForeground(new java.awt.Color(255, 255, 255));
        Regester.setText("REGESTER");
        Regester.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Regester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegesterActionPerformed(evt);
            }
        });
        getContentPane().add(Regester);
        Regester.setBounds(150, 250, 200, 60);
        Regester.setContentAreaFilled(false);

        LogIn.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        LogIn.setForeground(new java.awt.Color(255, 255, 255));
        LogIn.setText("LOG IN");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });
        getContentPane().add(LogIn);
        LogIn.setBounds(150, 330, 200, 60);
        LogIn.setContentAreaFilled(false);
        LogIn.getAccessibleContext().setAccessibleName("");

        Exit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Exit.setForeground(new java.awt.Color(153, 153, 153));
        Exit.setText("EXIT");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(170, 430, 154, 40);
        Exit.setContentAreaFilled(false);
        Exit.setBorderPainted(false);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\5th term\\- Java\\Dawarly\\Capture.PNG")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -1, 521, 520);

        setSize(new java.awt.Dimension(537, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegesterActionPerformed
        SignUp sign_up = new SignUp ();
        sign_up.show();
    }//GEN-LAST:event_RegesterActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
        LogIn log = new LogIn();
        log.show();
    }//GEN-LAST:event_LogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu menu = new Menu();
                menu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton LogIn;
    private javax.swing.JButton Regester;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
